In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [3]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
train.drop(columns=['Cabin'],inplace=True)
test.drop(columns=['Cabin'],inplace=True)

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 32.8+ KB

In [10]:
train['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [11]:
train['Embarked'].fillna('S',inplace=True)

C:\Users\cc\AppData\Local\Temp\ipykernel_15692\535005595.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Embarked'].fillna('S',inplace=True)

In [12]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [13]:
test['Fare'].value_counts()

Fare
7.7500     21
26.0000    19
13.0000    17
8.0500     17
7.8958     11
           ..
7.8208      1
8.5167      1
78.8500     1
52.0000     1
22.3583     1
Name: count, Length: 169, dtype: int64

In [14]:
test['Fare'].fillna(test['Fare'].mean(),inplace=True)

C:\Users\cc\AppData\Local\Temp\ipykernel_15692\3411113445.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Fare'].fillna(test['Fare'].mean(),inplace=True)

In [15]:
test.isnull().sum()

PassengerId     0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        0
dtype: int64

In [16]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C

In [17]:
train=pd.get_dummies(train,columns=['Sex'],drop_first=True)

In [18]:
test=pd.get_dummies(test,columns=['Sex'],drop_first=True)

In [19]:
train.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,S,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,S,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,S,True

In [20]:
test.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  418.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.840500
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [21]:
train['Age'].fillna(train['Age'].median(), inplace=True)

C:\Users\cc\AppData\Local\Temp\ipykernel_15692\486169235.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Age'].fillna(train['Age'].median(), inplace=True)

In [22]:
test['Age'].fillna(test['Age'].median(),inplace=True)

C:\Users\cc\AppData\Local\Temp\ipykernel_15692\309680536.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Age'].fillna(test['Age'].median(),inplace=True)

In [23]:
test.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Sex_male       0
dtype: int64

In [24]:
train['Age']=train['Age'].astype('int')

In [25]:
test['Age']=test['Age'].astype('int')

In [26]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Age          891 non-null    int64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Embarked     891 non-null    object
 10  Sex_male     891 non-null    bool
dtypes: bool(1), float64(1), int64(6), object(3)
memory usage: 70.6+ KB

In [27]:
train

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22,1,0,A/5 21171,7.2500,S,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38,1,0,PC 17599,71.2833,C,False
2,3,1,3,"Heikkinen, Miss. Laina",26,0,0,STON/O2. 3101282,7.9250,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35,1,0,113803,53.1000,S,False
4,5,0,3,"Allen, Mr. William Henry",35,0,0,373450,8.0500,S,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27,0,0,211536,13.0000,S,True
887,888,1,1,"Graham, Miss. Margaret Edith",19,0,0,112053,30.0000,S,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",28,1,2,W./C. 6607,23.4500,S,False
889,890,1,1,"Behr, Mr. Karl Howell",26,0,0,111369,30.0000,C,True
890,891,0,3,"Dooley, Mr. Patrick",32,0,0,370376,7.7500,Q,True

In [28]:
train.drop(columns=['Ticket'],inplace=True)

In [29]:
test.drop(columns=['Ticket'],inplace=True)

In [30]:
train.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Fare,Embarked,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22,1,0,7.2500,S,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38,1,0,71.2833,C,False
2,3,1,3,"Heikkinen, Miss. Laina",26,0,0,7.9250,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35,1,0,53.1000,S,False
4,5,0,3,"Allen, Mr. William Henry",35,0,0,8.0500,S,True

In [31]:
train['Embarked'].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [32]:
train['Embarked'] = train['Embarked'].map({'S': 0, 'C': 1,'Q':2})
test['Embarked'] = test['Embarked'].map({'S': 0, 'C': 1,'Q':2})

In [33]:
train['Title'] = train['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
train.drop('Name', axis=1, inplace=True)

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\cc\AppData\Local\Temp\ipykernel_15692\2319591336.py:1: SyntaxWarning: invalid escape sequence '\.'
  train['Title'] = train['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

In [34]:
test['Title'] = test['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
test.drop('Name', axis=1, inplace=True)

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\cc\AppData\Local\Temp\ipykernel_15692\3895068713.py:1: SyntaxWarning: invalid escape sequence '\.'
  test['Title'] = test['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

In [35]:
train

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex_male,Title
0,1,0,3,22,1,0,7.2500,0,True,Mr
1,2,1,1,38,1,0,71.2833,1,False,Mrs
2,3,1,3,26,0,0,7.9250,0,False,Miss
3,4,1,1,35,1,0,53.1000,0,False,Mrs
4,5,0,3,35,0,0,8.0500,0,True,Mr
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27,0,0,13.0000,0,True,Rev
887,888,1,1,19,0,0,30.0000,0,False,Miss
888,889,0,3,28,1,2,23.4500,0,False,Miss
889,890,1,1,26,0,0,30.0000,1,True,Mr
890,891,0,3,32,0,0,7.7500,2,True,Mr

In [36]:
test

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex_male,Title
0,892,3,34,0,0,7.8292,2,True,Mr
1,893,3,47,1,0,7.0000,0,False,Mrs
2,894,2,62,0,0,9.6875,2,True,Mr
3,895,3,27,0,0,8.6625,0,True,Mr
4,896,3,22,1,1,12.2875,0,False,Mrs
...,...,...,...,...,...,...,...,...,...
413,1305,3,27,0,0,8.0500,0,True,Mr
414,1306,1,39,0,0,108.9000,1,False,Dona
415,1307,3,38,0,0,7.2500,0,True,Mr
416,1308,3,27,0,0,8.0500,0,True,Mr
417,1309,3,27,1,1,22.3583,1,True,Master

In [37]:
mapping = {'Mr':0, 'Miss':1, 'Mrs':2, 'Master':3, 'Rare':4}
train['Title'] = train['Title'].map(mapping)
test['Title'] = test['Title'].map(mapping)

In [38]:
train['Title'].value_counts()

Title
0.0    517
1.0    182
2.0    125
3.0     40
Name: count, dtype: int64

In [39]:
train['Title'].fillna(1,inplace=True)

C:\Users\cc\AppData\Local\Temp\ipykernel_15692\3939541708.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Title'].fillna(1,inplace=True)

In [40]:
test['Title'].fillna(1,inplace=True)

C:\Users\cc\AppData\Local\Temp\ipykernel_15692\641801097.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Title'].fillna(1,inplace=True)

In [41]:
train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
Sex_male       0
Title          0
dtype: int64

In [42]:
train

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex_male,Title
0,1,0,3,22,1,0,7.2500,0,True,0.0
1,2,1,1,38,1,0,71.2833,1,False,2.0
2,3,1,3,26,0,0,7.9250,0,False,1.0
3,4,1,1,35,1,0,53.1000,0,False,2.0
4,5,0,3,35,0,0,8.0500,0,True,0.0
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27,0,0,13.0000,0,True,1.0
887,888,1,1,19,0,0,30.0000,0,False,1.0
888,889,0,3,28,1,2,23.4500,0,False,1.0
889,890,1,1,26,0,0,30.0000,1,True,0.0
890,891,0,3,32,0,0,7.7500,2,True,0.0

In [43]:
test

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex_male,Title
0,892,3,34,0,0,7.8292,2,True,0.0
1,893,3,47,1,0,7.0000,0,False,2.0
2,894,2,62,0,0,9.6875,2,True,0.0
3,895,3,27,0,0,8.6625,0,True,0.0
4,896,3,22,1,1,12.2875,0,False,2.0
...,...,...,...,...,...,...,...,...,...
413,1305,3,27,0,0,8.0500,0,True,0.0
414,1306,1,39,0,0,108.9000,1,False,1.0
415,1307,3,38,0,0,7.2500,0,True,0.0
416,1308,3,27,0,0,8.0500,0,True,0.0
417,1309,3,27,1,1,22.3583,1,True,3.0

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split

In [45]:
x=train.drop(columns=['Survived'])
y=train['Survived']

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=.25)

In [47]:
test = test.reindex(columns=x.columns, fill_value=0)

In [48]:
model=LogisticRegression()

In [49]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

C:\Users\cc\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [51]:
accuracy_score(y_test,y_pred)

0.7892376681614349

In [52]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)

0.7982062780269058

In [53]:
model=XGBClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)

0.8161434977578476

In [54]:
model=RandomForestClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)

0.8295964125560538

In [55]:
model.fit(x,y)
test_pred=model.predict(test)

In [56]:
submission = pd.DataFrame({
    'PassengerId': test['PassengerId'],
    'Survived': test_pred
})

In [57]:
submission

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]